const PLANS = { love: 299, memorias: 599, forever: 999 };
const json = (data, status=200, extra={}) => new Response(JSON.stringify(data), {status, headers:{'content-type':'application/json;charset=UTF-8','cache-control':'no-store',...extra}});
const id = () => crypto.randomUUID();
const token = () => crypto.randomUUID().replaceAll('-','') + crypto.randomUUID().replaceAll('-','');
const slugify = s => (s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,50);
async function uniqueSlug(env, base){let s=base||'nossa-historia'; for(let i=0;i<20;i++){const r=await env.DB.prepare('SELECT id FROM stories WHERE slug=?').bind(s).first(); if(!r)return s; s=base+'-'+Math.floor(100+i*7);} throw new Error('slug_unavailable');}
function requireToken(req, story){const h=req.headers.get('Authorization')||''; const supplied=h.startsWith('Bearer ')?h.slice(7):''; return !!supplied && !!story && supplied===story.edit_token;}
async function pagarPost(env,path,body,key){const raw=JSON.stringify(body); const ts=Date.now().toString(); const nonce=crypto.randomUUID(); const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw)); const hex=[...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join(''); const canonical=[ts,nonce,'POST',new URL(env.PAGAR_API_BASE_URL+path).pathname,hex].join('\n'); const secret=env.PAGAR_SIGNING_SECRET; if(!secret) throw new Error('PAGAR_SIGNING_SECRET_missing'); const keyData=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']); const sig=await crypto.subtle.sign('HMAC',keyData,new TextEncoder().encode(canonical)); const sigHex=[...new Uint8Array(sig)].map(x=>x.toString(16).padStart(2,'0')).join(''); const r=await fetch(env.PAGAR_API_BASE_URL+path,{method:'POST',headers:{Authorization:'Bearer '+env.PAGAR_API_KEY,'Content-Type':'application/json','Idempotency-Key':key,'X-Pagar-Timestamp':ts,'X-Pagar-Nonce':nonce,'X-Pagar-Signature':'v1='+sigHex},body:raw}); const data=await r.json(); if(!r.ok) throw new Error(data.message||'payment_rejected'); return data;}
async function verifyPagarWebhook(env,raw,header){const parts=Object.fromEntries((header||'').split(',').map(p=>p.trim().split('='))); const ts=Number(parts.t), received=parts.v1||''; if(!Number.isFinite(ts)||Math.abs(Date.now()/1000-ts)>300||!/^[a-f0-9]{64}$/.test(received)||!env.PAGAR_WEBHOOK_SECRET)return false; const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(env.PAGAR_WEBHOOK_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']); const sig=await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(ts+'.'+raw)); const expected=[...new Uint8Array(sig)].map(x=>x.toString(16).padStart(2,'0')).join(''); return expected===received;}
async function publishOrder(env, ref, ok=true){const order=await env.DB.prepare('SELECT * FROM orders WHERE reference=?').bind(ref).first(); if(!order)return; await env.DB.prepare('UPDATE orders SET status=?,paid_at=CASE WHEN ?=1 THEN CURRENT_TIMESTAMP ELSE paid_at END WHERE id=?').bind(ok?'PAID':'FAILED',ok?1:0,order.id).run(); if(ok)await env.DB.prepare('UPDATE stories SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind('published',order.story_id).run();}
export default {async fetch(req,env){const u=new URL(req.url);
if(req.method==='GET'&&u.pathname.startsWith('/api/public/story/')){const slug=u.pathname.split('/').pop(); const story=await env.DB.prepare('SELECT id,slug,name1,name2,start_date,phrase,message,music,theme,status,plan FROM stories WHERE slug=? AND status=?').bind(slug,'published').first(); if(!story)return json({error:'not_found'},404); const events=await env.DB.prepare('SELECT event_date,title,body FROM events WHERE story_id=? ORDER BY event_date').bind(story.id).all(); const photos=await env.DB.prepare('SELECT url,sort_order FROM photos WHERE story_id=? ORDER BY sort_order').bind(story.id).all(); return json({...story,events:events.results,photos:photos.results});}
if(req.method==='GET'&&u.pathname.startsWith('/media/')){const key=decodeURIComponent(u.pathname.slice(7)); const obj=await env.MEDIA.get(key); if(!obj)return new Response('Not found',{status:404}); const h=new Headers(); obj.writeHttpMetadata(h); h.set('cache-control','public,max-age=31536000,immutable'); return new Response(obj.body,{headers:h});}
if(req.method==='POST'&&u.pathname==='/api/stories'){const b=await req.json(); if(!b.name1||!b.name2)return json({error:'names_required'},400); const storyId=id(), editToken=token(), slug=await uniqueSlug(env,slugify(`${b.name1}-${b.name2}`)); await env.DB.prepare('INSERT INTO stories(id,owner_id,slug,edit_token,name1,name2,start_date,phrase,message,music,theme,plan) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(storyId,'anonymous',slug,editToken,b.name1,b.name2,b.startDate||null,b.phrase||'',b.message||'',b.music||'',b.theme||'rose',b.plan||'memorias').run(); return json({id:storyId,slug,editToken,status:'draft'});}
if(req.method==='PUT'&&u.pathname.startsWith('/api/stories/')){const storyId=u.pathname.split('/').pop(); const story=await env.DB.prepare('SELECT * FROM stories WHERE id=?').bind(storyId).first(); if(!story)return json({error:'not_found'},404); if(!requireToken(req,story))return json({error:'unauthorized'},401); const b=await req.json(); await env.DB.prepare('UPDATE stories SET name1=?,name2=?,start_date=?,phrase=?,message=?,music=?,theme=?,plan=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(b.name1||story.name1,b.name2||story.name2,b.startDate??story.start_date,b.phrase??story.phrase,b.message??story.message,b.music??story.music,b.theme||story.theme,b.plan||story.plan,storyId).run(); if(Array.isArray(b.events)){await env.DB.prepare('DELETE FROM events WHERE story_id=?').bind(storyId).run(); for(const e of b.events.slice(0,30))await env.DB.prepare('INSERT INTO events(id,story_id,event_date,title,body) VALUES(?,?,?,?,?)').bind(id(),storyId,e.date||null,e.text||'Moment',e.body||'').run();} return json({ok:true});}
if(req.method==='POST'&&u.pathname.startsWith('/api/stories/')&&u.pathname.endsWith('/photos')){const parts=u.pathname.split('/'); const storyId=parts[3]; const story=await env.DB.prepare('SELECT * FROM stories WHERE id=?').bind(storyId).first(); if(!story)return json({error:'not_found'},404); if(!requireToken(req,story))return json({error:'unauthorized'},401); const b=await req.json(); if(!b.dataUrl||!/^data:image\/(jpeg|jpg|png|webp);base64,/i.test(b.dataUrl))return json({error:'invalid_image'},400); const raw=b.dataUrl.split(',')[1]; if(raw.length>4_500_000)return json({error:'image_too_large'},413); const type=(b.dataUrl.match(/^data:(image\/[^;]+);/)||[])[1]||'image/jpeg'; const bytes=Uint8Array.from(atob(raw),c=>c.charCodeAt(0)); const ext=type.split('/')[1].replace('jpeg','jpg'); const key=`${storyId}/${crypto.randomUUID()}.${ext}`; await env.MEDIA.put(key,bytes,{httpMetadata:{contentType:type}}); const url=`/media/${key}`; const count=await env.DB.prepare('SELECT COUNT(*) AS n FROM photos WHERE story_id=?').bind(storyId).first(); const sort=Number(count?.n||0); await env.DB.prepare('INSERT INTO photos(id,story_id,url,sort_order) VALUES(?,?,?,?)').bind(id(),storyId,url,sort).run(); return json({ok:true,url});}
if(req.method==='POST'&&u.pathname.startsWith('/api/orders/')){const storyId=u.pathname.split('/').pop(); const b=await req.json(); const plan=b.plan||'memorias'; const amount=PLANS[plan]; if(!amount)return json({error:'invalid_plan'},400); const story=await env.DB.prepare('SELECT id,slug,status,edit_token FROM stories WHERE id=?').bind(storyId).first(); if(!story)return json({error:'not_found'},404); if(!requireToken(req,story))return json({error:'unauthorized'},401); const orderId=id(), reference='PS-'+orderId.slice(0,8).toUpperCase(); await env.DB.prepare('INSERT INTO orders(id,story_id,reference,plan,amount_mzn,payment_method) VALUES(?,?,?,?,?,?)').bind(orderId,storyId,reference,plan,amount,b.method||null).run(); if(!env.PAGAR_API_KEY)return json({orderId,reference,amount,status:'PENDING',setupRequired:true}); try{const method=(b.method||'MPESA').toUpperCase().replace('-',''); const p=await pagarPost(env,'/payments',{reference,title:'Para Sempre - '+plan,description:'Publicação de página de memória digital',amountMzn:amount,method,payerPhone:b.phone},'payment:'+orderId); const pay=p.payment||p; await env.DB.prepare('UPDATE orders SET payment_id=?,status=? WHERE id=?').bind(pay.id||null,pay.status||'PROCESSING',orderId).run(); return json({orderId,reference,amount,status:pay.status,paymentId:pay.id,checkoutUrl:pay.checkoutUrl||pay.checkout_url||p.checkoutUrl||p.checkout_url||null});}catch(e){await env.DB.prepare('UPDATE orders SET status=? WHERE id=?').bind('FAILED',orderId).run(); return json({error:e.message,orderId,reference},502);}}
if(req.method==='GET'&&u.pathname.startsWith('/api/orders/')){const orderId=u.pathname.split('/').pop(); const o=await env.DB.prepare('SELECT id,reference,status,amount_mzn,payment_method,story_id FROM orders WHERE id=?').bind(orderId).first(); if(!o)return json({error:'not_found'},404); return json(o);}
if(req.method==='POST'&&u.pathname==='/api/pagar/webhook'){const raw=await req.text(); if(!(await verifyPagarWebhook(env,raw,req.headers.get('Pagar-Signature')||'')))return new Response('invalid signature',{status:401}); const event=JSON.parse(raw), eventId=req.headers.get('Pagar-Event-Id'); if(!eventId)return new Response('missing event id',{status:400}); const existing=await env.DB.prepare('SELECT event_id FROM webhook_events WHERE event_id=?').bind(eventId).first(); if(existing)return new Response('ok'); await env.DB.prepare('INSERT INTO webhook_events(event_id) VALUES(?)').bind(eventId).run(); const payment=event.data||{}; const ref=payment.reference; if(event.event==='payment.succeeded'&&ref)await publishOrder(env,ref,true); else if(event.event==='payment.failed'&&ref)await publishOrder(env,ref,false); return new Response('ok');}
if(req.method==='GET'&&u.pathname==='/api/health')return json({ok:true,service:'para-sempre',version:'5.0'}); return env.ASSETS.fetch(req);}};
